version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 2.2
    commands:
      - apt-get update
      - apt-get install -y jq

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=12345678912.dkr.ecr.us-east-1.amazonaws.com/hello-world
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)-$BUILD_BRANCH
      - LATEST=latest-$BUILD_BRANCH
  build:
    commands:
      - echo Build started on `date`
      - dotnet restore
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$LATEST .
      - docker tag $REPOSITORY_URI:$LATEST $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$LATEST
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
